spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emsdb
    username: emsuser
    password: emspassword

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080


jwt:
  secret: ZmQ4MzU4Nzk2Y2Y4ZmJlMWM3MzQ0ZjYxYzY5M2M4MjY1OTQxYjA5M2RmMzY2M2M0ZmU5NzU3MWQ4MzNmM2FjNg==
  expiration: 3600000