spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emsdb
    username: emsuser
    password: emspassword

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080